src/Entity/Ressource.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RessourceRepository")
 */
class Ressource
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Video;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getVideo()
    {
        return $this->Video;
    }

    public function setVideo($Video)
    {
        $this->Video = $Video;

        return $this;
    }
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->video;
    }
}

src/Controller/front/ProfileController.php
<?php


namespace App\Controller\front;


use App\Entity\Candidat;
use App\Entity\LigneProposition;
use App\Entity\OffreEmplois;
use App\Entity\Responsable;
use App\Entity\Video;
use App\Repository\AboutRepository;
use App\Repository\AProposRepository;
use App\Repository\OffreEmploisRepository;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profil/responsale", name="profil_client")
     */
    public function profil_responsable()
    {
        return $this->render('profile/responsable.html.twig');
    }

    /**
     * @Route("/profil/responsable/cvvideos", name="cvvideo")
     */

    public function video(VideoRepository $repository)
    {


        $res = $repository->searchVideoCVT();
        return $this->render('profile/cvvideo.html.twig',[
            'cv'=>$res
        ]);

    }

    /**
     * @Route("/profil/responsable/entretien", name="entretien")
     */
    public function entretien(VideoRepository $entretien)
    {
        $res= $entretien->searchVideoEntretientt();
        return $this->render('profile/entretien.html.twig',[
            'entretien'=> $res
        ]);
    }


    /**
     * @Route("/edit/resp/client/{id}", name="edit_profile_client")
     * @param Responsable $responsable
     */
    public function EditResponsable(Responsable $responsable)
    {

    }

    /**
     * @Route("/profil/candidat", name="profil_candidat")
     * @param AboutRepository $repository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function profil_candidat(AboutRepository $repository, VideoRepository $videoRepository)
    {
        $user=$this->getUser();
        $about=$repository->findOne($user);
        $video=$videoRepository->findOne($user);
        dump($video);
        return $this->render('profile/candidat.html.twig',[
            'about'=>$about==[]? null: $about[0],
            'video'=>$video==[]? null: $video,
        ]);
    }
    /**
     * @Route("/projet/encour/", name="en_cours")
     */
    public function projetEnCours(OffreEmploisRepository $repository)
    {
        $user=$this->getUser();
        $offres=$repository->findOffres($user);
        $nbrRec = count($offres);
        return $this->render('profile/encours.html.twig',[
            'offre'=>$offres,
            'nbr'=>$nbrRec
        ]);
    }

    /**
     * @Route("/projet/encour/detail/{id}", name="detail_cours")
     * @param OffreEmploisRepository $repository
     * @param OffreEmplois $offreEmplois
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function projetEnCoursDetails(OffreEmploisRepository $repository, OffreEmplois $offreEmplois)
    {
        $user=$this->getUser();
        $offre=$repository->findAcces($user, $offreEmplois);
        $offres=$repository->findOffres($user);
        dump($offre[0]->getLignePropositions());
        return $this->render('profile/encoursDetails.html.twig',[
            'offre'=>$offres,
            'prop'=>$offre
        ]);
    }

    /**
     * @Route("/select/candidat/{id}", name="select")
     * @param LigneProposition $ligneProposition
     * @param EntityManagerInterface $em
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function selectCandidat(LigneProposition $ligneProposition, EntityManagerInterface $em)
    {
        $ligneProposition->setStatus(true);
        $em->persist($ligneProposition);
        $em->flush();
        $idOffre=$ligneProposition->getProposition()->getOffreEmplois()->getId();
        return $this->redirectToRoute('detail_cours',['id'=>$idOffre]);
    }

    /**
     * @Route("/deselect/candidat/{id}", name="deselect")
     * @param LigneProposition $ligneProposition
     * @param EntityManagerInterface $em
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deselectCandidat(LigneProposition $ligneProposition, EntityManagerInterface $em)
    {
        $ligneProposition->setStatus(false);
        $em->persist($ligneProposition);
        $em->flush();
        $idOffre=$ligneProposition->getProposition()->getOffreEmplois()->getId();
        return $this->redirectToRoute('detail_cours',['id'=>$idOffre]);
    }

    /**
     * @Route("/voir/candidat/{id}", name="voir_candidat")
     */
    public function voirCandiat(Candidat $candidat, AboutRepository $repository)
    {
        $apropos=$repository->findOne($candidat);

        return $this->render('profile/candiatPropose.html.twig',[
            'candidat'=>$candidat,
            'about'=>$apropos[0]->getContenu()
        ]);
    }
}

templates/profile/cvvideo.html.twig
{% extends 'front.html.twig' %}

{% block style %}
    <style>
        .btn-2{
            border-radius: 50px;
            padding: 10px 40px;
            color:#ffde59;
            font-weight: bold;
            font-family:'Arimo', sans-serif;
            background: #545454;
            border:2px solid #ffde59;
        }
        .btn-2:hover{
            border-radius: 50px;
            padding: 10px 40px;
            color: #545454;
            font-weight: bold;
            font-family:'Arimo', sans-serif;
            background: linear-gradient(#ffde59,#ffbd59,#ff914d);
            border:2px solid #545454;
        }
    </style>
{% endblock %}

{% block body %}


    <section class="container-fluid" style="padding-top:100px;padding-bottom:80px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2 style="font-family:'Raleway', sans-serif;
                  color:#545454;
                  font-weight: bold;
                  font-size: 45px;
                  text-align:center;
                   padding-bottom:30px;"> <strong>CV Vidéo</strong>
                    </h2>
                    <h3 data-aos="zoom-in"  data-aos-duration="600"
                        style="color: #ff914d;
                  font-family: 'Arimo', sans-serif;
                  text-align: center;
                  padding-bottom:30px;">ENTREZ DANS L'ERE DU RECRUTEMENT 2.0</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h4 data-aos="fade-right" data-aos-duration="800"
                        style="font-weight: bold;padding-bottom: 20px;text-align: center;">Pour les candidats</h4>
                    <div style="font-size: 20px;text-align: justify;" >
                        <p data-aos="fade-right" data-aos-duration="1000">
                            Le CV Vidéo est un moyen de se démarquer de la concurrence et d'aboutir facilement à un entretien d'embauche.
                        </p>
                        <p data-aos="fade-right" data-aos-duration="1400">
                            <strong> Corban propose:</strong><br>
                            - La conception et le tournage de votre CV Vidéo.<br>
                            - Sa diffusion auprès des potentiels recruteurs.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h4 data-aos="fade-left" data-aos-duration="800"
                        style="font-weight: bold;padding-bottom: 20px;text-align: center;">Pour les recruteurs</h4>
                    <div style="font-size: 20px;text-align: justify;" >
                        <p data-aos="fade-left" data-aos-duration="1000">
                            Le CV Vidéo vous permet de faire immédiatement une différenciation du profil du candidat recherché et donne une vision plus globale du candidat dans des conditions idéales.
                        </p>
                        <p data-aos="fade-left" data-aos-duration="1400">
                            Corban propose:<br>
                            - L'accès à notre base de donnée de CV Vidéos triés sur le volet.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="container-fluid" style="background-color: #f5f5f5; padding: 80px 80px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2 style="font-family:'Raleway', sans-serif;
                  color:#545454;
                  font-weight: bold;
                  font-size: 45px;
                  text-align:center;
                   padding-bottom:30px;">Tous les CV Vidéos</h2>
                </div>
            </div>
            {% if app.user %}
                <div class="row" id="cvvideo" style="text-align: center;">
                    {% if cv|length != 0 %}
                        {% for c in cv %}
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div style="background-color:#2d2d2c; width:100%;text-align: center">
                                    <div><a href="{{ path('show',{id: c.id}) }}"><video poster="/assets/img/video2.png" src="{{ c.video }}"width="100%" height="300px"></video><p style="color:#fff;background-color:#ffbd59;padding-bottom:10px;padding-top:10px;font-size:20px;"><strong>{{ c.description}}</strong></p></a></div></div></div>
                        {% endfor %}
                    {% else  %}
                        <p>Aucun cv vidéo pour l'instant</p>
                    {% endif %}
                </div>
            {% else %}
           <center><h2>Vous ne pouvez pas voir ça il faut se connecter <a href="{{ path('connexion') }}">Connection</a> </h2></center>
            {% endif %}

        </div>
    </section>

    <section class="container-fluid" style="background: linear-gradient(#ffde59,#ffbd59);padding-top: 60px;padding-bottom: 60px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div style="text-align: center;font-family:'Raleway', sans-serif; ">
                        <h2 style="color: #545454;font-size: 40px;"
                            data-aos="fade-right" data-aos-duration="800">
                            <strong>Pour plus d'information</strong>
                        </h2>
                        <h3 style="color: #fff;padding-top: 20px;"
                            data-aos="fade-left" data-aos-duration="900">
                            <strong>CONTACTEZ-NOUS</strong>
                        </h3>
                    </div>
                    <div  style="padding-top: 20px;text-align: center;font-size: 20px;"
                          data-aos="fade-right" data-aos-duration="1000">
                        <a href="{{ path('contact')}}">
                            <button type="button" class="btn-2 ">
                                <strong>CONTACT</strong>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/profile/cvvideos.html.twig
{% extends 'front.html.twig' %}

{% block style %}
{% endblock %}

{% block body %}
    <div class="container-fluid" style="padding-top: 150px;padding-bottom: 50px;">
    <div class="container">
        <div class="row" id="tem" style="text-align:center;">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><div><video controls src="{{ cv.video }}" width="720px" height="450px"></video></div>

            </div>


            <hr>

            <div class="row" style="text-align: center;color: #fff;font-size: 30px;">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2 data-aos="fade-left"data-aos-duration="800">
                        <strong>TOUS LES CV VIDEOS</strong>
                    </h2>
                </div>
            </div>
            <hr>
            <div class="row" id="cvvideo" style="text-align: center;padding-top: 30px;">
                {% if cvs|length != 0 %}
                    {% for c in cvs %}
                        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"><div style="background-color:#2d2d2c; width:100%;text-align: center"><div><a href="{{ path('show',{id: c.id}) }}"><video poster="/assets/img/video2.png" src="{{ c.video }}"width="100%" height="300px"></video><p style="color:#fff;background-color:#ffbd59;padding-bottom:10px;padding-top:10px;font-size:20px;"><strong>{{ c.description }}</strong></p></a></div></div></div>
                    {% endfor %}
                {% else  %}
                    <p></p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/profile/encours.html.twig
{% extends 'front.html.twig' %}
{% block style %}
    <style>
        .head{
             background: linear-gradient(to right, #32a2c8 ,#005876);
            width: 100%;
            height: 50%;
            padding-left: 7%;
            padding-top: 8%;
            position: relative;
        
        }
        .nom{
            color: #ffffff;
            font-weight: bold;
        }
        .responsabilite{
            color: #ffffff;
        }
        .bg-light{
            background-color: #F1F1F1;
        }

        .gallery-container {
            position: relative;
            width: 100%;
            border-width: 7px;
            border-color: #FFFFFF;
            border-style: solid;
            box-shadow: 0px 0px 2px 0px rgba(0,0,0,0.1);
            cursor: pointer;
        }

        .image {
            display: block;
            width: 100%;
            height: auto;
        }

        .overlay {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background-color: #FFFFFF;
            overflow: hidden;
            width: 100%;
            height: 0;
            transition: .3s ease;
        }

        .gallery-container:hover .overlay {
            height: 50px;
        }

        .text {
            font-family: 'Noto Sans KR', sans-serif;
            font-size: 14px;
            line-height: 1.3em;
            color: #414141;
            font-weight: bold;
        .small{
            font-family: 'Noto Sans KR', sans-serif;
            font-size: 13px;
            line-height: 1.3em;
            color: #999999;
        }
        .view-btn{
            right: 10px;
            top: 12px;
            position: absolute;
            color: #000000;
            font-weight: 500;
            border-width: 1px;
            border-color: #e7e7e7;
            border-style: solid;
            font-family: 'Noto Sans KR', sans-serif;
            font-size: 13px;
        &:hover{
             border-color: #333333;
         }
        }
        }

        .carousel-control-next, .carousel-control-prev {
            width: auto;
        }
        .modal-open .modal {
            overflow-x: hidden;
            overflow-y: auto;
            background-color: rgba(0,0,0,0.5);
        }

        .modal-body {
            position: relative;
            -ms-flex: 1 1 auto;
            flex: 1 1 auto;
            padding: 0rem;
        }

        .modal-thumbs{
            min-height: 150px;
        label{
            font-family: 'Noto Sans KR', sans-serif;
            font-size: 14px;
            line-height: 1.3em;
            font-weight: 700;
            color: #333333;
            padding-left: 5px;
        }
        ul{
            padding: 0;
        li{
            list-style: none;
            width: 25%;
            float: left;
        @media (max-width: 768px) {
            width: 50%;
        }
        .border {
            display: inline-block;
            position: relative;
        }
        .border::after {
            content: '';
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            box-shadow: inset 0 0 0 0 rgba(255,255,255,.5);
            transition: box-shadow .1s ease;
            cursor: pointer;
        }
        .border:hover::after {
            box-shadow: inset 0 0 0 10px rgba(255,255,255,.5);
        }
        img {
            display: block;
            position: relative;
        }
        }
        }
        }

        .arrow-left{
            float: left;
            left: 0px;
            padding: 50px;
            position: fixed;
            height: 100%;
        @media (max-width: 768px) {
            display:none!important;
        }
        &:hover{
             background-color: rgba(0,0,0,0.3);
         }
        }

        .carousel-inner{
            float: left;
        }

        .arrow-right{
            float: left;
            right: 0px;
            padding: 50px;
            position: fixed;
            height: 100%;
        @media (max-width: 768px) {
            display: none!important;
        }
        &:hover{
             background-color: rgba(0,0,0,0.3);
         }
        }

         .ret{
    color:#3b88a3;
  }
  .ret:hover{
    color:#545454; 
  }
  .btn-008{
    background: none;
    font-size: 20px;
    padding: 10px;
    width: 75%;
  }
  .btn-008:hover{
    background: #fff;
    border-radius: 50px;
    padding: 15px;
  }
  span{
    color:#f8f8f8; 
  }
  span:hover{
    color:#3b88a3; 
  }
    </style>
{% endblock %}
{% block body %}
<div class="head">
        <div style="color: #fff; 
                    font-weight: bold;
                    font-family: 'Raleway', sans-serif;
                    font-size: 40px;
                    padding-bottom: 50px;">PROJET EN <br> COURS
        </div>
    </div>
<div style="text-align: center; font-size: 20px;font-weight: bold;
                padding-top: 10px;padding-bottom: 7px; background: #fff;margin-top: 10px;">
      <a href="#">
        <p class="ret">Recrutement en cours</p> 
      </a>
    </div>  

<section class="container-fluid" style="background-color:#f8f8f8; padding-top: 40px;padding-bottom: 40px;">
  <div class="container">
    <div class="row">
      <div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
          <div style="width: 500px; height: 300px; padding: 15px; background-color: #fff;box-shadow: 2px 2px 1px grey;
                    text-align: center;font-weight: bold;">
            <p style="color: grey;padding-top: 15px;font-size: 30px;">
              Nombre de recrutement
            </p>
            <p style="color: #f4960e;padding-top: 30px;font-size: 80px;">
              {{ nbr }}
            </p> 
          </div>
        </div>
      </div>
      <div style="text-align:right;background:linear-gradient(to right,#c1edec,#f7e5bf);">
        <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12">
          <div style="width: 600px;height: 300px;padding: 15px;">
          </div>
        </div>
      </div>
    </div>  
  </div>
</section>

<section class="container-fluid" style="background-color:#f8f8f8; padding-top: 50px;padding-bottom: 80px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-12; col-md-12 col-sm-12 col-xs-12">
        {% for f in offre %}
        <div class="btn-008" style="text-align: justify;">
          <a href="{{ path('detail_cours', {id:f.id}) }}" style="color: #545454;">
            {{ f.titre }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span href="{{ path('detail_cours', {id:f.id}) }}"> Suivre à l'avancement</span>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>  


{% endblock %}

templates/profile/entretien.html.twig
{% extends 'front.html.twig' %}

{% block style %}
    <style>
        .btn-2{
            border-radius: 50px;
            padding: 10px 40px;
            color:#ffde59;
            font-weight: bold;
            font-family:'Arimo', sans-serif;
            background: #545454;
            border:2px solid #ffde59;
        }
        .btn-2:hover{
            border-radius: 50px;
            padding: 10px 40px;
            color: #545454;
            font-weight: bold;
            font-family:'Arimo', sans-serif;
            background: linear-gradient(#ffde59,#ffbd59,#ff914d);
            border:2px solid #545454;
        }
    </style>
{% endblock %}

{% block body %}


    <section class="container-fluid" style="padding-top:100px;padding-bottom:80px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2 style="font-family:'Raleway', sans-serif;
                  color:#545454;
                  font-weight: bold;
                  font-size: 45px;
                  text-align:center;
                   padding-bottom:30px;"> <strong>Entretien Vidéo</strong>
                    </h2>
                    <h3 data-aos="zoom-in"  data-aos-duration="600"
                        style="color: #ff914d;
                  font-family: 'Arimo', sans-serif;
                  text-align: center;
                  padding-bottom:30px;">ENTREZ DANS L'ERE DU RECRUTEMENT 2.0</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h4 data-aos="fade-right" data-aos-duration="800"
                        style="font-weight: bold;padding-bottom: 20px;text-align: center;">Le concept</h4>
                    <div style="font-size: 20px;text-align: justify;" >
                        <p data-aos="fade-right" data-aos-duration="1000">
                            Cette plateforme digitale dédiée au recrutement 2.0 met en relation les candidats à la recherche de nouvelle opportunité de travail et les entreprises à la recherche de meilleur
                            talents.
                        </p>
                        <p data-aos="fade-right" data-aos-duration="1400">
                            Inscrivez-vous et ayez accès à des entretiens différés des candidats potentiels.
                        </p>
                        <p data-aos="fade-right" data-aos-duration="1000">Contactez-nous pour plus d'information.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h4 data-aos="fade-left" data-aos-duration="800"
                        style="font-weight: bold;padding-bottom: 20px; text-align: center;">Les avantages</h4>
                    <div style="font-size: 20px;" >
                        <p style="text-align: center;" data-aos="fade-left" data-aos-duration="1400">
                            ●  Accélérer le processus de recrutement<br>
                            ● Large choix des candidats potentiels
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="container-fluid" style="background-color: #f5f5f5; padding: 80px 80px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2 style="font-family:'Raleway', sans-serif;
                  color:#545454;
                  font-weight: bold;
                  font-size: 45px;
                  text-align:center;
                   padding-bottom:30px;">Tous les Entretiens Vidéos</h2>
                </div>
            </div>
            {% if app.user %}
                <div class="row" id="entretientvideo" style="text-align: center;">
                    {% if entretien|length != 0 %}
                        {% for e in entretien %}
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div style="background-color: #2d2d2c; width:100%;text-align: center">
                                    <div><a href="{{ path('show_tient',{id: e.id}) }}"><video  poster="/assets/img/video3.png" src="{{ e.video }}"width="100%" height="300px"></video><p style="color:#fff;background-color:#ffbd59;padding-bottom:10px;padding-top:10px;font-size:20px;"><strong>{{ e.description }}</strong></p></a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else  %}
                        <p>Aucun entretient vidéo pour l'instant</p>
                    {% endif %}

                </div>
            {% else %}
                <center><h2>Vous ne pouvez pas voir ça il faut se connecter <a href="{{ path('connexion') }}">Connection</a> </h2></center>
            {% endif %}
        </div>
    </section>

    <section class="container-fluid" style="background: linear-gradient(#ffde59,#ffbd59);padding-top: 60px;padding-bottom: 60px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div style="text-align: center;font-family:'Raleway', sans-serif; ">
                        <h2 style="color: #545454;font-size: 40px;"
                            data-aos="zoom-in" data-aos-duration="800">
                            <strong>Pour plus d'information</strong>
                        </h2>
                        <h3 style="color: #fff;padding-top: 20px;"
                            data-aos="fade-left" data-aos-duration="900">
                            <strong>CONTACTEZ-NOUS</strong>
                        </h3>
                    </div>
                    <div  style="padding-top: 20px;text-align: center;font-size: 20px;"
                          data-aos="fade-right" data-aos-duration="1000">
                        <a href="{{path('contact')}}">
                            <button type="button" class="btn-2 ">
                                <strong>CONTACT</strong>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/profile/entretienvideo.html.twig
{% extends 'front.html.twig' %}

{% block style %}
{% endblock %}

{% block body %}
    <div class="container-fluid" style="padding-top: 150px;padding-bottom: 50px;
                                     background-image: url(/assets/images/service/cvvideo/43.jpg);">
        <div class="container">
            <div class="row" id="tem" style="text-align:center;">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div><iframe style="height:400px;width:800px;text-align: center;" src="{{ entretient.video }}" width="720px" height="450px"></iframe></div>
                </div>
            </div>


            <hr>

            <div class="row" style="text-align: center;color: #fff;font-size: 30px;">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h2 data-aos="fade-left"data-aos-duration="800">
                        <strong>TOUS LES ENTRETIENS VIDEOS</strong>
                    </h2>
                </div>
            </div>
            <hr>
            <div class="row" id="entretientvideo" style="text-align: center;padding-top: 30px;">
                {% if entretients|length != 0 %}
                    {% for e in entretients %}

                        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                            <div style="background-color: #2d2d2c; width:100%;text-align: center">
                                <div><a href="{{ path('show_tient',{id: e.id}) }}"><video  poster="/assets/img/video3.png" src="{{ e.video }}"width="100%" height="300px"></video><p style="color:#fff;background-color:#ffbd59;padding-bottom:10px;padding-top:10px;font-size:20px;"><strong>{{ e.description }}</strong></p></a>
                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% else  %}
                    <p></p>
                {% endif %}

            </div>
        </div>
    </div>



{% endblock %}