src/Entity/Coopteur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CoopteurRepository")
 */
class Coopteur implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=13)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="8" , minMessage="Votre mot de passe est trop court")
     *
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Les deux mot de passe doivent etre identique")
     */
    public $confirmpassword;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\UserType", inversedBy="coopteurs")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pays;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Cooptation", mappedBy="coopteur")
     */
    private $cooptations;

    public function __construct()
    {
        $this->cooptations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getType(): ?UserType
    {
        return $this->type;
    }

    public function setType(?UserType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }


    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        // TODO: Implement getRoles() method.
        return ['ROLE_USER'];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Cooptation[]
     */
    public function getCooptations(): Collection
    {
        return $this->cooptations;
    }

    public function addCooptation(Cooptation $cooptation): self
    {
        if (!$this->cooptations->contains($cooptation)) {
            $this->cooptations[] = $cooptation;
            $cooptation->setCoopteur($this);
        }

        return $this;
    }

    public function removeCooptation(Cooptation $cooptation): self
    {
        if ($this->cooptations->contains($cooptation)) {
            $this->cooptations->removeElement($cooptation);
            // set the owning side to null (unless already changed)
            if ($cooptation->getCoopteur() === $this) {
                $cooptation->setCoopteur(null);
            }
        }

        return $this;
    }
}

templates/formulaire/about.html.twig
{% extends 'front.html.twig' %}
{% block style %}
    <style>
        .ri{
            width: 50%;
            height: 550px;
            padding-top: 100px;
        }
        .head{
            background-color: #cb8402;
            height: 9em;
            padding-top: 5.5%;
        }
        .img{
            margin-top: 1.5%;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="head">
        {% set img = (app.user.photo == null)? '/user/user.jpg' : '/candidat/' ~ app.user.photo %}
        {#        <div class="nom">{{ app.user.client.nom }}</div>#}
        <center>
            <div class="img">
                <img src="{{ img }}" width="10%" style="height: 110px;border: #9A9A9A solid 2px; border-radius: 100px"><br>
            </div>
        </center>
    </div>
        <center>
            <div class="ri">
                {{ form_start(form) }}
                {{ form_row(form.contenu) }}
                <input type="submit" value="Enregistrer" class="btn btn-info">
                {{ form_end(form) }}
            </div>
        </center>
{% endblock %}

templates/formulaire/candidature.html.twig
{% extends 'front.html.twig' %}

{% block style %}
<style>
    .center {
        margin: auto;
        width: 50%;
        height: 45%;
        background-color: #fff ;
        padding-bottom: 5%;
    }
    .btn-8{
        text-align: center;
        font-weight: bold;
        padding: 10px 40px;
        font-size: 25px;
        color: #545454;
        background: #6495ED;
        border-radius: 10px;
        border: none;

    }
    .btn-8:hover{
        font-weight: bold;
        padding: 10px 40px;
        font-size: 25px;
        border-radius: 10px;
        background:#545454;
        border:2px solid #fff;
        color: #fff;
    }

</style>
{% endblock %}

{% block body %}

<section class="container-fluid" style="background:linear-gradient(#ffde59,#ffbd59);
										padding-top:80px;
										padding-bottom: 30px;">
    <div class="container" style="padding-top: 5%; padding-bottom: 5%;">
        <div class="center">
                {% for message in app.flashes('info') %}
            <div class="alert alert-success" style="text-align: center">
                    {{ message }}
            </div>
                {% endfor %}

            <div class="row">
                <div class="col-md-12" style="font-family:'Raleway', sans-serif;
						   color: #000000;
						   text-align: center;
						   font-size: 45px;
						   font-weight: bold;
						   padding-bottom: 15px;
						   padding-top: 50px">
                    Postuler

                </div>
            </div>
            {{ form_start(form) }}

                <div class="row"  style="padding-bottom: 25px; ">
                    <div class="col-md-12" style="padding-left: 10%; padding-right: 15%" >

                        {{ form_row(form.cv) }}
                    </div>

                </div>
                <div class="row" style="padding-bottom: 25px; ">
                    <div class="col-md-12" style="padding-left: 10%;  padding-right: 15%">

                        {{ form_row(form.lm) }}
                    </div>
                </div>
                <div class="row" style="padding-bottom: 25px; ">
                    <div class="col-md-12" style="padding-left: 10%;  padding-right: 15%">

                        {{ form_row(form.ds) }}
                    </div>
                </div>
            <div class="row" style="text-align: center;padding-top: 5px;">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                    <input type="submit" class="btn-8" value="ENVOYER"/>
                </div>

            </div>

            {{ form_end(form) }}
        </div>
    </div>
</section>
{% endblock %}

templates/formulaire/cooptation.html.twig
{% extends 'front.html.twig' %}

{% block style %}
    <style>
        .center {
            margin: auto;
            width: 50%;
            height: 45%;
            background-color: #fff ;
            padding-bottom: 5%;
        }
        .btn-8{
            text-align: center;
            font-weight: bold;
            padding: 10px 40px;
            font-size: 25px;
            color: #545454;
            background: #6495ED;
            border-radius: 10px;
            border: none;

        }
        .btn-8:hover{
            font-weight: bold;
            padding: 10px 40px;
            font-size: 25px;
            border-radius: 10px;
            background:#545454;
            border:2px solid #fff;
            color: #fff;
        }

    </style>
{% endblock %}

{% block body %}

    <section class="container-fluid" style="background:linear-gradient(#ffde59,#ffbd59);
										padding-top:80px;
										padding-bottom: 30px;">
        <div class="container" style="padding-top: 5%; padding-bottom: 5%;">
            <div class="center">
                {% for message in app.flashes('info') %}
                    <div class="alert alert-success" style="text-align: center">
                        {{ message }}
                    </div>
                {% endfor %}

                <div class="row">
                    <div class="col-md-12" style="font-family:'Raleway', sans-serif;
						   color: #000000;
						   text-align: center;
						   font-size: 45px;
						   font-weight: bold;
						   padding-bottom: 15px;
						   padding-top: 50px">
                        Coopter

                    </div>
                </div>
                {{ form_start(form) }}

                <div class="row"  style="padding-bottom: 25px; ">
                    <div class="col-md-12" style="padding-left: 10%; padding-right: 15%" >

                        {{ form_row(form.cv) }}
                    </div>

                </div>

                <div class="row" style="text-align: center;padding-top: 5px;">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                        <input type="submit" class="btn-8" value="ENVOYER"/>
                    </div>

                </div>

                {{ form_end(form) }}
            </div>
        </div>
    </section>
{% endblock %}

templates/formulaire/inscriptionCandidat.html.twig
{% extends 'front.html.twig' %}
{% block title %}Inscription Candidat{% endblock %}
    {% block style %}
        <style>
            .cont{
                width: 75%;
                text-align: left;
                background-color: rgba(192,192,192,0.6);
                padding-left: 15px;
                padding-right: 15px;
                font-weight: bold;
                color: white;

            }

        </style>
    {% endblock %}
{% block body %}
    <div class="container-fluid" style="padding-top: 4%; padding-bottom: 5%; background-image: url(/assets/images/accueil/1.jpg); background-size: cover">
        <center>
            <div class="cont">

                <h1 style="text-align: center">Inscription candidat</h1>
                {{ form_start(form) }}

                <div class="row" >
                    <div class="col-md-12 " >{{ form_row(form.photo,{'attr':{'class':'btn btn-primary', 'placeholder':'Votre Photo'} })}}</div>

                </div>


                <div class="row">
                    <div class="col-md-6" >   {{ form_row(form.nom,{'attr':{'class':'text' ,'placeholder':'Votre Nom'}}) }}</div>
                    <div class="col-md-6">   {{ form_row(form.dateNaissance) }}</div>

                </div>
                <div class="row">
                    <div class="col-md-6">  {{ form_row(form.candidatSexe) }}</div>
                    <div class="col-md-6">  {{ form_row(form.situation) }}</div>

                </div>
                <div class="row">
                    <div class="col-md-6">   {{ form_row(form.email,{'attr':{'placeholder': 'Votre Email'}}) }}</div>
                    <div class="col-md-6">  {{ form_row(form.telephone,{'attr':{'placeholder': 'Votre Numero de telephone'}}) }}</div>

                </div>
                <div class="row">
                    <div class="col-md-6">  {{ form_row(form.pays ,{'attr':{'placeholder': 'Votre Pays'}}) }}</div>
                    <div class="col-md-6">   {{ form_row(form.ville ,{'attr':{'placeholder': 'Votre Ville'}}) }}</div>

                </div>
                <div class="row">
                    <div class="col-md-6">   {{ form_row(form.adresse ,{'attr':{'placeholder': 'Votre Adresse'}}) }}</div>
                    <div class="col-md-6">   {{ form_row(form.username ,{'attr':{'placeholder': 'Votre Pseudo'}}) }}</div>
                </div>
                <div class="row">
                    <div class="col-md-6">    {{ form_row(form.password ,{'attr':{'placeholder': 'Entrer votre mot de passe'}}) }}</div>
                    <div class="col-md-6">    {{ form_row(form.confirmPassword ,{'attr':{'placeholder': 'confirmer votre mot de passe'}}) }}</div>
                </div>
                <center>
                    <input type="submit" class="btn btn-primary" style="width: 50%; height: 40px" value="S'INSCRIRE">
                </center>
                {{ form_end(form) }}
                <br><br>
            </div>
        </center>
    </div>





{% endblock %}

templates/formulaire/inscriptionCoopteur.html.twig
{% extends 'front.html.twig' %}
{% block title %}Inscription Coopteur{% endblock %}
    {% block style %}
        <style>
            .cont{
                width: 75%;
                text-align: left;
                background-color: rgba(192,192,192,0.6);
                padding-left: 15px;
                padding-right: 15px;
                font-weight: bold;
                color: white;

            }
        </style>
    {% endblock %}
{% block body %}
    <div class="container-fluid" style="padding-top: 4%; padding-bottom: 5%; background-image: url(/assets/images/accueil/4.jpg); background-size: cover">
        <center>
        <div class="cont">

        <h1 style="text-align: center">Inscription coopteur</h1>
        {{ form_start(form) }}

        <div class="row" >
            <div class="col-md-12" >{{ form_row(form.photo,{'attr':{'class':'btn btn-primary' , 'placeholder':'Votre Photo'}}) }}</div>

        </div>


        <div class="row">
            <div class="col-md-6" >  {{ form_row(form.nom,{'attr':{'id':'text' , 'placeholder' : 'Votre Nom'}  } ) }}</div>
            <div class="col-md-6">   {{ form_row(form.telephone,{'attr':{'placeholder' : 'Votre Numero de telephone '}  }) }}</div>

        </div>
         <div class="row">
             <div class="col-md-6">  {{ form_row(form.adresse,{'attr':{'placeholder' : 'Votre adresse'}  }) }}</div>
             <div class="col-md-6">  {{ form_row(form.email,{'attr':{'placeholder' : 'Votre E-mail'}  }) }}</div>

         </div>
        <div class="row">
            <div class="col-md-6">  {{ form_row(form.entreprise ,{'attr':{'placeholder' : 'Votre Entreprise'}  }) }}</div>
            <div class="col-md-6">  {{ form_row(form.pays ,{'attr':{'placeholder' : 'Votre Pays'}  }) }}</div>

        </div>
        <div class="row">
            <div class="col-md-6">  {{ form_row(form.ville,{'attr':{'placeholder' : 'Votre Ville'}  }) }}</div>
            <div class="col-md-6">   {{ form_row(form.username,{'attr':{'placeholder' : 'Votre Pseudo'}  }) }} </div>

        </div>
        <div class="row">
            <div class="col-md-6">   {{ form_row(form.password,{'attr':{'placeholder' : 'Mot de passe'}  }) }}</div>
            <div class="col-md-6">   {{ form_row(form.confirmpassword,{'attr':{'placeholder' : 'Confirmer votre mot de passe'}  }) }}</div>
        </div>
                <center>
                    <input type="submit" class="btn btn-primary" style="width: 50%; font-size: 60%; height: 40px" value="S'INSCRIRE">
                </center>
                {{ form_end(form) }}
            <br><br>
        </div>
        </center>
    </div>





{% endblock %}

templates/formulaire/login.html.twig
{% extends 'front.html.twig' %}

    {% block title %}Connexion{% endblock %}
    {% block style %}
        <style>
            .cont{
                background-color: rgba(192,192,192,0.6);
                margin-left: 25%;
                margin-right: 22%;
                font-weight: bold;
            }
        </style>

    {% endblock %}
{% block body %}
    <div class="container-fluid" style="padding-top:10%; padding-bottom: 5%; background-image: url('/public/assets/images/apropos/74 1.jpg '); background-size: cover;">

        <div class="cont">
            <form method="post" action="{{ path('connexion') }}">

                <h1 style="font-size:3vw; text-align: center">Connexion</h1>
                {% if error %}
                    <div class="error" style="text-align: center; background-color: rgba(255,30,20,0.4); color: red; font-weight: bold; height: 35px; text-shadow: black 1px 1px; font-size: 19px">
                        {{ error.messageKey | trans(error.messageData, 'security') }}
                    </div>
                    <br>
                {% endif %}
                <br>

                <center>

                    <input type="text" name="_username" required placeholder="Votre Pseudo" style="height: 3em; border-radius: 5px; width: 45%; color: #0b0b0b; " value="{{ lastUsername }}" placeholder="Entrer votre Pseudo">
                    <br><br>
                    <input required class="input-mini" type="password" name="_password" style="height: 3em; border-radius: 5px; width: 45%;  color: #0b0b0b; " placeholder="Votre mot de passe">
                    <br><br>
                    <input class="btn btn-lg btn-primary" style="height: 3.5em; width: 45%" type="submit" name="" value="SE CONNECTER">

                    <p style="padding-bottom: 7px;">Pour vous s'inscrir entant que <b style="color: #f4960e;">Candidat</b> <a href="{{ path('inscription_candidat') }}">cliquer ici</a></p>
                    <p>Pour vous s'inscrir entant que <b style="color: #f4960e;">Coopteur</b> <a href="{{ path('inscription_coopteur') }}">cliquer ici</a></p><BR><br>
                </center>

            </form>
        </div>
    </div>



{% endblock %}

templates/formulaire/newFormation.html.twig
{% extends 'front.html.twig' %}

{% block style %}
    <style>
        .for{
            width: 50%;
            padding-top: 80px;
            text-align: left;
            padding-bottom: 40px;
        }
    </style>
{% endblock %}
{% block body %}
    <center>
        <div class="for">
            <h2>Nouvelle formation</h2><hr>
            {{ form_start(form) }}
            {{ form_row(form.university) }}
            {{ form_row(form.diplome) }}
            {{ form_row(form.filier) }}
            {{ form_row(form.debut) }}
            {{ form_row(form.fin) }}
            <input type="submit" class="btn btn-primary" value="Enregistrer">
            {{ form_end(form) }}
        </div>
    </center>
{% endblock %}

templates/formulaire/newParcours.html.twig
{% extends 'front.html.twig' %}

{% block style %}
    <style>
        .for{
            width: 50%;
            padding-top: 80px;
            text-align: left;
            padding-bottom: 40px;
        }
    </style>
{% endblock %}
{% block body %}
    <center>
        <div class="for">
            <h2>Ton nouvelle parcours</h2><hr>
            {{ form_start(form) }}
            {{ form_row(form.entreprise) }}
            {{ form_row(form.poste) }}
            {{ form_row(form.lieu) }}
            {{ form_row(form.debut) }}
            {{ form_row(form.fin) }}
            <input type="submit" class="btn btn-primary" value="Enregistrer">
            {{ form_end(form) }}
        </div>
    </center>
{% endblock %}